# Generated by Django 3.0.4 on 2020-03-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advice',
            name='tags',
            field=models.CharField(max_length=128),
        ),
    ]
